# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: local
    hooks:
      - id: run-tests
        name: pytest on tests/ (manual)
        entry: pytest tests
        language: system
        pass_filenames: false
        stages: [manual]   # 👈 Only runs if you ask pre-commit to run it manually