from .environments import CONFIG, ENV
from .constants import (
    ALLOWED_ACTION_INPUT_FIELDS, SUPPORTED_FIELDS,
    ACTIONS_PER_PAGE, EVENTS_PER_PAGE, REWARDS_PER_PAGE, LOGS_PER_PAGE,
    BADGE_TYPES, STACKABLE_TYPES, PUBLISHABLE_REWARD_TYPES,
    EXCLUDED_LOG_FIELDS,
    CUSTOM_DISCORD_EMOJI, UNICODE_EMOJI,
)

# Re-export environment-specific values for convenience
MOD_ROLE_IDS                   = CONFIG["MOD_ROLE_IDS"]
EMBED_CHANNEL_ID               = CONFIG["EMBED_CHANNEL_ID"]
EVENT_ANNOUNCEMENT_CHANNEL_ID  = CONFIG["EVENT_ANNOUNCEMENT_CHANNEL_ID"]
TICKET_CHANNEL_ID              = CONFIG["TICKET_CHANNEL_ID"]
REWARD_PRESET_CHANNEL_ID       = CONFIG["REWARD_PRESET_CHANNEL_ID"]
REWARD_PRESET_ARCHIVE_CHANNEL_ID = CONFIG["REWARD_PRESET_ARCHIVE_CHANNEL_ID"]